Fix material_used and category issues
unstructuredstudio/zubhub pull request #1120
Opened 2024-03-01 08:03 UTC by coderatomy

fixes validation errors

2024-03-01 17:31 UTC, coderatomy commented
more work has to be done since this `params` are extensively use https://github.com/search?q=repo%3Aunstructuredstudio%2Fzubhub%20props.params&type=code

2024-03-03 22:56 UTC, NdibeRaymond requested changes

2024-03-03 22:56 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/views/create_project/script.js
> +    materials_used: Yup.array().required('required'),
No idea why we keep removing  validations instead of getting them to work properly

2024-03-03 22:56 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/views/create_project/script.js
> +    materials_used: Yup.array().required('required'),
If we are going to work on this then we should fix it completely

2024-03-04 13:09 UTC, NdibeRaymond commented
> fixes #1121 fixes validation errors

* fixed  eslint  errors
*  improvements to App.js  and PageWrapper.jsx
* removed materials_used and category field validation issues. Those require their own issue and PR

2024-03-04 13:20 UTC, merged