Issue209 : Error Notification on Sign Up gets hidden on mobile UX
unstructuredstudio/zubhub pull request #412
Opened 2022-04-18 16:10 UTC by alicendeh

## Summary

When signing up on mobile device, any notification (eg password mismatch etc.) shows up at top (below heading) when you tap Sign Up. Since the form is long, the user is unaware of what they are missing and the app just seems stuck when you tap Sign Up

##Fix
The error is  shown on top of screen  like other notifications using standard notification system

Closes #209

## Changes

-Added a toast in Signupscript

## Screenshots 

![Screenshot from 2022-04-18 17-09-32](https://user-images.githubusercontent.com/58989178/163837444-9f9405ff-13f1-4a93-a989-79647de7607f.png)

2022-04-18 16:18 UTC, tuxology approved these changes
LGTM :rainbow_flag: Will wait for @NdibeRaymond to merge this. I haven't tested but it looks simple.

2022-04-18 20:33 UTC, alicendeh commented
OKay sure

2022-04-19 01:31 UTC, NdibeRaymond requested changes

2022-04-19 01:31 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/views/signup/signupScripts.js
> +      toast.error(
hello @alicendeh thanks for submitting this PR!
Few changes and we can merge this. It looks like you aren't localizing messages here. Here is what you can do about it:
* Search for "toast" on your code editor and observe how it's being used in other places.
* Create entries for this error message in the signup section of each locale file (en/translation.json and hi/translation.json) then add the message to the en file.
* search for english to hindi on google and use the provided translator to covert the english translation to  hindi then paste in in the corresponding location in the hi/translation.json file

2022-04-19 03:07 UTC, alicendeh commented on zubhub_frontend/zubhub/src/views/signup/signupScripts.js
> +      toast.error(
Oh yes, I completely forgot the system is a bilingual system. My bad.
Let me modify that .

2022-04-19 03:11 UTC, alicendeh commented
Done @NdibeRaymond. Please have a look

2022-04-21 01:35 UTC, NdibeRaymond approved these changes

2022-04-21 01:40 UTC, merged