Bug fixes: social share buttons
unstructuredstudio/zubhub pull request #444
Opened 2022-04-22 08:33 UTC by saxytony

## Summary

Fix functional and style bugs for social share buttons

Closes #434 

## Changes

* FB and WA buttons now open new windows
* Copy to clipboard bug fixed, working now
* Hide social share buttons on mobile
* Update screen size dependent stylings in projectDetailsStyles

## Screenshots

<img width="471" alt="image" src="https://user-images.githubusercontent.com/90807954/164649758-cf669027-ffb0-4363-a328-5b27fc54e385.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/90807954/164649885-482fa94a-3909-4922-a902-6ff627727fbb.png">

2022-04-22 12:51 UTC, NdibeRaymond requested changes

2022-04-22 12:51 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/components/social_share_buttons/socialShareButtons.jsx
> +                alert('Link copied to clipboard: ' + url);
plain string should be localized. Also we use toaster, not native alert. you can refer to other places in the codebase where toaster is used.

2022-04-22 12:51 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/components/social_share_buttons/socialShareButtons.jsx
> +                alert('Something went wrong!');
same here. localization and no use of native alert function

2022-04-22 12:51 UTC, NdibeRaymond commented on zubhub_frontend/zubhub/src/components/social_share_buttons/socialShareButtons.jsx
> +const styles = makeStyles({
style should be moved to the styles folder, just like is the case for other components

2022-04-26 02:14 UTC, saxytony commented
@NdibeRaymond Hi Raymond, I have added localization features to the component and moved the styles to the right place.

2022-04-26 02:39 UTC, ajain1921 approved these changes

2022-04-26 02:39 UTC, merged