Display uploaded project image preview
unstructuredstudio/zubhub pull request #482
Opened 2022-05-18 18:50 UTC by souad988

## Summary

Display preview of project images that a user uploads in create project form.
Closes #164

## Changes

- Add Grid container  and Paper components to display uploaded images.
- Make Grid items responsive to screen size.

## Screenshots
![preview md](https://user-images.githubusercontent.com/59707859/169126675-c70a01a9-7a99-42a3-9c50-4ca4084869a9.PNG)
![preview xs](https://user-images.githubusercontent.com/59707859/169126700-1cbcd161-dbb6-419b-966b-b24cbbf68c9d.PNG)

2022-05-19 15:32 UTC, souad988 commented
Hi @srish  
i hope you are doing well, would you please review my PR, and there is a behavior that i noticed and want to open an issue for, when i click the button to upload an image it overrides the images i already selected while it is supposed to append the new images to the uploaded images list, then we can add delete buttons to the preview if the user want's to remove an image.

2022-05-30 23:06 UTC, tuxology commented
@souad988 Thanks, this is a great feature and will really improve the UX. I tested this a bit more and here is some intial   feedback before I begin full review:

1. For normal desktop width, the image preview sizes look ok. However for larger widths (eg. 1594x2454 that I tested) the images become stretched. See below
 
![image](https://user-images.githubusercontent.com/3373857/171065640-c3e31188-8bc1-4aa3-9371-bf5a47b75519.png)

2. For smaller widths such as mobile size same issues exists. See below

![image](https://user-images.githubusercontent.com/3373857/171065704-ecf89773-44bb-4edc-820c-73508d0811c7.png)

For resolving these, we should should render image in one style, maybe just a fix 1:1 ratio always with max widths for all responsive  theme "breakpoints" 

3. The styling of images should also follow a bit of consistent styling. I suggest we put images with same round edges as the radius of Description input box int the form and and also have an option to remove them using a Red cross button. (imagine a white  :x:  in a red circle  :red_circle:) placed on top right corner as below

![image](https://user-images.githubusercontent.com/3373857/171066372-5799e3b1-3321-4bcc-b188-15d463422c6e.png)

It is possible that this action of selectively removing images might not exist, but we can work on it. This also goes in line with the suggestion you have here https://github.com/unstructuredstudio/zubhub/pull/482#issuecomment-1131877028 wherein we can also allow users to append images - thus completing a very good UX feature of selectively removing or adding images.

2022-06-23 09:46 UTC, souad988 commented
Hi @tuxology  @srish @kamthamc 
would you please review this PR, I made preview images resizes with screen size with 1:1 ratio , Added icon and function to remove selectively a preview image.

![image preview mobile](https://user-images.githubusercontent.com/59707859/175270254-afa61df5-4e80-4415-b10f-3e74fdb2c113.PNG)
![image preview remove icon](https://user-images.githubusercontent.com/59707859/175270262-6740210f-3621-4781-9c71-53f77ad791b8.PNG)

2022-06-23 16:33 UTC, souad988 commented
in case you don't want to use fontawsome icons we can replace by `import CloseIcon from '@mui/icons-material/Close';`

2022-07-04 06:49 UTC, srish requested changes
@souad988 I tested this feature. Its a really cool one :) Though, I think it has a few issues still that I am sharing below: 
* The images are still getting shrinked. For example, I tried uploading the following images: 
<img width="1439" alt="Screen Shot 2022-07-03 at 11 33 10 PM" src="https://user-images.githubusercontent.com/288353/177095893-b72a20e4-56d6-4ab5-9590-01a799466c23.png">
Notice the ones that have text - second in the first row and last in the second row. And, now compare them with the original ones below. Note that this behavior is seen in desktop (3072 × 1920) as well as mobile resolution.

<img width="300" src="https://user-images.githubusercontent.com/288353/177096103-bfa0f2e5-8bc2-453a-be28-7f3b2e610d1b.jpeg">

<img width="300" src="https://user-images.githubusercontent.com/288353/177096109-a5376a29-3e64-4567-ae93-a1797e4b76d5.jpeg">

* Another issue is that after uploading a few images, when I try to add some more, the new images replace the previously uploaded images.

* After the project is created with a few images, when I try to edit it, I don't see the preview. It goes missing.

* When I remove an image, the counter doesn't get updated. 

* Finally, I see that there are bunch of errors on the console, which may have been caused due to other features. Just bringing this up so you can maybe verify and ensure that this feature doesn't contribute to any new errors on the console. 

cc @tuxology

2023-03-10 23:22 UTC, Mara-mma commented
Hi @srish @tuxology this is my idea for solving the issue
![kite_unstructuredstudio](https://user-images.githubusercontent.com/105233065/224445939-a826692d-97f3-42a3-8b51-635c1cf88d2c.jpg)
![kite 2_unstructuredstudio](https://user-images.githubusercontent.com/105233065/224446027-f8bd40dc-8c52-4965-ac13-af4be72d51bd.jpg)

2023-05-05 13:56 UTC, closed without merging