Use formik nested objects
unstructuredstudio/zubhub pull request #532
Opened 2022-09-09 18:25 UTC by souad988

## Summary

Description of PR here...
Changed form state management to be fully handled by formik .
Add deserialize function to refactor activity object and fill the form for edit.
Add video upload validation for video file or url and disable video inputs after one is used.
Add save activity functionality.

2022-09-10 08:15 UTC, srish requested changes
@souad988 Most of the changes I've suggested include text changes, reducing the character limit for fields, and a few minor issues here and there. I have not come across any major issue so far, all suggestions have to do with minor improvements so that's a good thing :)

First, about helper text and placeholders. I think we don't need both. Let's remove helper text and only keep the placeholder. Maybe there is one place where we might need to retain helper text (likely materials). Use the text I've suggested for various fields. Once we finalize the changes, I can suggest some changes for the translation file for "Hindi."

Then, I saw that there is quite a lot of stuff that gets printed on the console. Make sure there are no errors, and they don't get printed as well.

Lastly, there is a bug in the progress bar; it is not working as intended. As I jump from Step 1 to 2, it is shown as complete. Take a look at it.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your title shouldn't be more than 100 characters",
Change text to "Less than 100 characters"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Name your Activity",
Change placeholder text to "Provide a title for your activity"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "motivation",
Make the "m" capital in the label so it becomes "Motivation"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "helperText": "Add motivation text",
Remove helper text

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your motivation shouldn't be more than 10,000 characters",
Change this text to "Less than 10000 characters"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Name your Activity",
Change text to "Title"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Add Learning Goals",
Remove "Add" from "Add Learning Goals"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your title shouldn't be more than 100 characters",
Re-thinking, I think we should reduce the limit to 50 chars

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your motivation shouldn't be more than 10,000 characters",
Re-thinking, I think we should reduce the limit to 500 chars

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your learning goals shouldn't be more than 10,000 characters",
Change the text to "Less than 1000 characters" and reduce the limit

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "helperText": "List some of this activity's learning goals",
Remove helperText

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +      "label": "what materials did you use?",
Change text to "Materials"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +      "helperText": "List some of the essential materials used to create this activity",
Change text "What materials did you use to develop this activity?" Where are we currently displaying this because I don't see it.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +      "encouragingText": "We strongly encourage you to upload an image containing all materials and tools used to create this activity",
Change text to "Add an image with all materials used"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Add Images"
It is a bit confusing that we are allowing uploading of only one image but here we say "Images" in the label. Maybe we say "Add Image"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "max": "your material shouldn't be more than 50 characters",
This error is not populating, instead I am seeing `createActivity.inputs.materials_used[0].errors.max`. In any case, let's change the text to "Less than 50 characters"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "required": "this field is required",
Let's make t in "this" capital for consistency.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "min": "your material should be at least 2 characters"
Let's change text to "Atleast two characters are required"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "required1": "At least one material is required!",
Let's change text to "Atleast one material is required"; so remove "!" mark for consistency and join "At" and "least".

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "helperText": "List some helpful facilitation tips",
Remove helper text

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "required": "This field is required"
Change the text to "Less than 1000 characters" and reduce the limit.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Facilitation tips",
Make "t" in "tips" capital for consistency

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Add Images of your activity",
Change text to "Demo Images"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "required": "This field is required",
Can we just use "required" and get rid of "required1"?

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step2.jsx
> +            fieldLabel={'Add a video if provided'}
Change the text here to "Demo Videos". I was wondering about the placement of this label separate from others as well, but not a big deal.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step2.jsx
> +            label={'ActivityVideo'}
When the video exceeds a limit, error is getting displayed as `createActivity.inputs.video.errors.maxVideoFileSize` on the screen instead of text

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step2.jsx
> +              uploadButtonLabel={'Upload Video'}
I think we should change text here to "Add Video" because for adding video URLs that makes more sense.

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Creation Steps",
Change text to "Making Process"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your creation step shouldn't be more than 10,000 characters",
Change text to "1000" characters and reduce the limit

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "label": "Add Step Image"
Change text to "Add Image"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "placeholder": "creation step",
Change the text to "What was your process for developing the activity? What were the various steps involved?"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "helperText": "List steps you followed to create this activity",
Remove helperText

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "placeholder": "Facilitation tips",
Change text to "How can educators engage learners in such an activity? What questions can they ask a learner about the activity? What kind of examples can they demonstrate?"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "placeholder": "List some of this activity's learning goals",
Change text to "What will someone learn from this activity?"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "placeholder": "Add motivation text",
Change the text to "Share your motivation for developing the activity"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "required": "describe creation process in at least one step ",
Change text to "Atleast one step is required"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "emptyStep": "step can't be empty provide either a description or an image"
Change text to "Provide either an image or description for a step"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "Inspiring Artist",
Perhaps we should change this to "Inspiring Person"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "placeholder": "Inspiring artist Bio",
Share the background of an inspiring artist, inventor, or educator who is the inspiration behind this activity or whose work relates to it

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "helperText": "Enter a Bio of your inspiring artist",
Remove helpertext

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "label": "Add Artist Image"
Change text to "Add Image"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "max": "your artist bio shouldn't be more than 10,000 characters",
Less than 1000 characters and reduce the limit

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step3.jsx
> +              label={'ArtistFullName'}
Lets change text to "Name"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +        "label": "inspiring Examples",
I capital in "inspiring" for consistency

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +          "label": "Add Example Image"
Change text to "Add Image"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +      "inspiringExemples": {
this variable has spelling mistake..

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step3.jsx
> +                            label={`Img-${key + 1} desc`}
Let's change this so it appears as "1. Image description"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/views/create_activity/create_activity_step3.jsx
> +                            label={`Img-${key + 1} credit`}
Let's change this so it appears "1. Image credit"

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/src/components/materialsUsed/materialsUsed.jsx
> +              label={`material-${index + 1}`}
Let's change this so it appears as:
1.
2.
3.

we need only number not material word for this one..

2022-09-10 08:15 UTC, srish commented on zubhub_frontend/zubhub/public/locales/en/translation.json
> +      "Next": "Next->",
Use the same icons we are using for "previous and next page buttons" on the homepage

2022-09-10 08:25 UTC, souad988 commented
> @souad988 Most of the changes I've suggested include text changes, reducing the character limit for fields, and a few minor issues here and there. I have not come across any major issue so far, all suggestions have to do with minor improvements so that's a good thing :)
> 
> First, about helper text and placeholders. I think we don't need both. Let's remove helper text and only keep the placeholder. Maybe there is one place where we might need to retain helper text (likely materials). Use the text I've suggested for various fields. Once we finalize the changes, I can suggest some changes for the translation file for "Hindi."
> 
> Then, I saw that there is quite a lot of stuff that gets printed on the console. Make sure there are no errors, and they don't get printed as well.
> 
> Lastly, there is a bug in the progress bar; it is not working as intended. As I jump from Step 1 to 2, it is shown as complete. Take a look at it.

Hi @srish thanks for the review, concerning the progress bar i think it shows as complete when you change one field and click next  only on edit mode because the form is already valid so the user should be able to save

2022-09-10 08:28 UTC, souad988 commented on zubhub_frontend/zubhub/src/components/materialsUsed/materialsUsed.jsx
> +              label={`material-${index + 1}`}
I got it 👍

2022-09-10 08:52 UTC, srish requested changes
@souad988 I also noticed that if we add a video url (e.g., youtube) thumbnail appears as broken. I think this one you can file as an issue and no need to fix yourself.

2022-09-10 09:04 UTC, srish requested changes
I found a bug in the "Add a video" field. If let say I enter in the video url box and exit without typing anything it assumes an input and screen freezes thereafter. On the console, I see the following msg:

> createActivityScripts.js:171 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at Object.<anonymous> (createActivityScripts.js:171:1)
    at runTest (createValidation.js:14:1)
    at validate (createValidation.js:101:1)
    at mixed.js:292:1
    at Array.map (<anonymous>)
    at mixed.js:291:1
    at async Promise.all (:3000/index 0)
(anonymous) @ createActivityScripts.js:171
runTest @ createValidation.js:14
validate @ createValidation.js:101
(anonymous) @ mixed.js:292
(anonymous) @ mixed.js:291
Promise.then (async)
handleInputBlur @ inputScripts.js:4
onBlur @ input.jsx:71
handleBlur @ InputBase.js:332
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
VM124:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)

2022-09-10 09:09 UTC, srish requested changes
There is another bug around creation steps. If I enter only the description for a step but not the image, I immediately see no error, and the "Submit for review" button also gets enabled and the progress bar appears as complete. When I click on it, I start seeing the submission in progress, and there is a loader on the screen, but the activity never gets published or created, it seems.

2022-09-10 09:12 UTC, srish commented
> > @souad988 Most of the changes I've suggested include text changes, reducing the character limit for fields, and a few minor issues here and there. I have not come across any major issue so far, all suggestions have to do with minor improvements so that's a good thing :)
> > First, about helper text and placeholders. I think we don't need both. Let's remove helper text and only keep the placeholder. Maybe there is one place where we might need to retain helper text (likely materials). Use the text I've suggested for various fields. Once we finalize the changes, I can suggest some changes for the translation file for "Hindi."
> > Then, I saw that there is quite a lot of stuff that gets printed on the console. Make sure there are no errors, and they don't get printed as well.
> > Lastly, there is a bug in the progress bar; it is not working as intended. As I jump from Step 1 to 2, it is shown as complete. Take a look at it.
> 
> Hi @srish thanks for the review, concerning the progress bar i think it shows as complete when you change one field and click next only on edit mode because the form is already valid so the user should be able to save

Yeah, I checked the progress bar again now that my backend setup is working fully, I think the behavior seems right for now.

2022-09-11 23:21 UTC, souad988 commented
> There is another bug around creation steps. If I enter only the description for a step but not the image, I immediately see no error, and the "Submit for review" button also gets enabled and the progress bar appears as complete. When I click on it, I start seeing the submission in progress, and there is a loader on the screen, but the activity never gets published or created, it seems.
the image is optional for making steps and the educator can describe creation process in only one step ,  I think the loading issue was due to something else i tried to reproduce the same issue but didn't happen

2022-09-11 23:28 UTC, souad988 commented
> @souad988 I also noticed that if we add a video url (e.g., youtube) thumbnail appears as broken. I think this one you can file as an issue and no need to fix yourself.

I added a refactorUrl function to fix this issue for youtube, vimeo and google drive videos  and also added a check for empty urls , so preview image of video and video url is correctly  working.

**next todo for video field:**
  - add upload to Cloudinary. 
  - and clear video url input on delete preview.

2023-05-05 13:57 UTC, closed without merging