Master 595
unstructuredstudio/zubhub pull request #621
Opened 2023-03-09 20:08 UTC by yaya-mamoudou

## Summary

Description of PR
This PR is in an addition to another merged [PR](https://github.com/unstructuredstudio/zubhub/pull/605).
After testing I realized that the user was still being able to submit an empty form, but this time when on mobile. 
I also observed an imparity of color balance in the input field when not being focused. 
Closes #595

## Changes

- Added the handleSubmit function to the second InputField
- Changed the colour of the input field to white when not focused and black when focused

## Screenshots
*Not focused*
<img width="740" alt="image" src="https://user-images.githubusercontent.com/57509871/224142696-ccb5aed8-ae9a-4ac8-9370-e0ad77f5a97c.png">

*Focused*
<img width="740" alt="image" src="https://user-images.githubusercontent.com/57509871/224142873-1f63d953-c197-4e35-a588-de014ba1b00b.png">

2023-03-09 22:59 UTC, yaya-mamoudou commented
@tuxology please review this PR when you can

2023-03-09 23:30 UTC, tuxology commented
@yaya-mamoudou I planned to merge a dark search bar change being submitted at https://github.com/unstructuredstudio/zubhub/pull/584 Do you think the darker one looks better? Also I agree with the input field focused issue. Keep this PR open I'd say, we will merge #584, then you can improve this one?

2023-03-09 23:34 UTC, yaya-mamoudou commented
Sure @tuxology. Let's do this that way.

2023-03-17 19:01 UTC, tuxology commented
@yaya-mamoudou Can we update it since the #584 is merged now?

2023-03-31 01:05 UTC, yaya-mamoudou commented
> @yaya-mamoudou Can we update it since the #584 is merged now?

@tuxology this PR was mainly to solve the issue with the search input on mobile submitting even when empty.
Should I do just that, or also include this style on the input when focused?

2023-04-13 21:28 UTC, tuxology requested changes
We'll merge after we remove focus/color changes. We'll on do the fix for empty submission on mobile for now

2023-04-13 21:28 UTC, tuxology commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +    '& .MuiInputBase-input': {
I think we can skip this. The current styling looks ok

2023-04-16 10:22 UTC, yaya-mamoudou commented
@tuxology this is ready to merge

2023-09-21 19:05 UTC, tuxology commented
Since too much has changed in top search bar, we will fix this subset of issue related to #605 later  - closing this

2023-09-21 19:05 UTC, closed without merging