fix: header responsiveness
unstructuredstudio/zubhub pull request #652
Opened 2023-03-12 20:04 UTC by Ammy198488

## Summary

Description 

In this pull request, I implemented a responsive design for the header section of the website. I used media queries to adjust the styling of the header for different screen sizes, making it look clean and organized on all devices. 
Closes #585 

## Changes

- Styles theme in index.js
- PageWrapper.js
- PageWrapperStyles.js
- BreadcrumbStyles.js

## Screenshots
![image 1](https://user-images.githubusercontent.com/74745072/224569890-0cbc7a4b-004a-4c74-aa81-7dc35c8ca8d0.png)

![image 2](https://user-images.githubusercontent.com/74745072/224569908-df962a98-cb96-45f5-9b9c-04b8fb6eff23.png)

![image 3](https://user-images.githubusercontent.com/74745072/224569917-e47df749-ed66-4a6d-9a5e-22cb68590c3e.png)

![image 4](https://user-images.githubusercontent.com/74745072/224569930-202b77f3-c545-4a67-9b68-ab87903144f1.png)

![image 5](https://user-images.githubusercontent.com/74745072/224569942-d1f40e4f-1536-4025-b537-d8d2a4b84521.png)

2023-03-13 11:07 UTC, tuxology commented
@Ammy198488 can you please rebase your branch and resolve merge conflicts?  In addition, the search bar is shown on lower resolutions along with the search icon. @iamatifmoin Can you help @Ammy198488 and do a review of this PR since you've already worked on this?

2023-03-13 11:32 UTC, Ammy198488 commented
Okay
For the images, I should show for other screen sizes right?

2023-03-13 13:53 UTC, iamatifmoin commented
> @Ammy198488 can you please rebase your branch and resolve merge conflicts? In addition, the search bar is shown on lower resolutions along with the search icon. @iamatifmoin Can you help @Ammy198488 and do a review of this PR since you've already worked on this?

Yes sure!

2023-03-13 13:56 UTC, iamatifmoin commented
@Ammy198488 
Do you know how to rebase and resolve merge conflicts? 
If not, then give me your Zulip ID, and I'll help you out.

2023-03-13 15:34 UTC, Ammy198488 commented
> @Ammy198488 Do you know how to rebase and resolve merge conflicts? If not, then give me your Zulip ID, and I'll help you out.

okay @iamatifmoin ID is ammy

2023-03-14 13:47 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/components/breadCrumb/breadCrumbStyle.js
> +    //width: '100%',
remove this line

2023-03-14 13:48 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +
close the block here. --> `},`

2023-03-14 13:53 UTC, iamatifmoin requested changes
I have added a few comments. 
Make the changes, and commit the code.
Everything else looks good.

2023-03-14 13:53 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
>      [theme.breakpoints.up('1168')]: {
remove this line

2023-03-14 13:53 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
>      [theme.breakpoints.down('1168')]: {
remove this line

2023-03-14 13:53 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/views/PageWrapper.jsx
> +        {/* dropdown */}
remove this line

2023-03-14 13:53 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/components/breadCrumb/breadCrumbStyle.js
> +    //width: '100%',
remove this line

2023-03-14 13:53 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +
close the block here --> `},`

2023-03-14 15:47 UTC, Ammy198488 commented
@iamatifmoin Thanks
Would look into it

2023-03-14 18:56 UTC, Ammy198488 commented
@tuxology @iamatifmoin All done and ready.

2023-03-15 07:47 UTC, iamatifmoin requested changes
@Ammy198488 
You have made some changes to the colours that will revert the changes made by #584.
Please make the changes requested in the comments.

2023-03-15 07:47 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +      backgroundColor: 'rgba(255,255,255,0.2)',
change this line to->

`backgroundColor: 'rgba(0,0,0,0.2)',`

2023-03-15 07:47 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +      backgroundColor: 'rgba(255,255,255,0.2)',
change this line to->

`backgroundColor: 'rgba(0,0,0,0.2)',`

2023-03-15 07:47 UTC, iamatifmoin commented on zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js
> +      color: 'black',
change this line to->

`color: 'white',`

2023-03-15 07:49 UTC, iamatifmoin commented
Also, is the width of the search bar for this screen-size alright or does it need to be bigger @tuxology?

![Zubhub](https://user-images.githubusercontent.com/97212195/225241840-d10a76fc-53ee-4b94-b8f6-90685bf034e8.png)

2023-03-15 14:12 UTC, iamatifmoin approved these changes
@tuxology 
everything looks good.

@Ammy198488 well done!

2023-03-15 22:08 UTC, tuxology approved these changes
LGTM 🌈

2023-03-15 22:12 UTC, tuxology commented
@Ammy198488 and @iamatifmoin Actually is it possible to centre the bar or extend the size to remaining width in relation to this: https://github.com/unstructuredstudio/zubhub/pull/652#issuecomment-1469510391 ?

2023-03-16 10:42 UTC, iamatifmoin commented
@tuxology 
Maybe you can merge this PR and I can do that in a new PR?
I think that would be better. What do you think?

2023-03-17 18:54 UTC, merged