#627 Rectified the merging of Email label inside input border when opened for the first time
unstructuredstudio/zubhub pull request #693
Opened 2023-03-19 20:20 UTC by cherish2003

## Summary
Email label is getting merged inside input border when open for the first time this issue can be solved by this PR

Closes #627 

## Changes

- Removed `labelWidth` property which is causing the bug
- Added `label` to the `outlined` component which allocates width statically

## Screenshots

![Screenshot from 2023-03-20 01-48-19](https://user-images.githubusercontent.com/88829894/226206704-6f4901e6-f3ee-4030-90f3-7416f55b62ab.png)

![Screenshot from 2023-03-20 01-48-41](https://user-images.githubusercontent.com/88829894/226206736-bc514d20-ca1b-48d8-acfa-2843ab946df4.png)

2023-03-19 20:21 UTC, cherish2003 commented
@tuxology @srish  kindly review the code and let me know any changes are required

2023-03-26 01:05 UTC, tuxology commented
@cherish2003 Any comments or updates on this? Are you still working on this?

2023-03-26 04:59 UTC, cherish2003 commented
> @cherish2003 Any comments or updates on this? Are you still working on this?

@tuxology No Sir i have done all the changes already this can be successfully merged

2023-03-28 02:15 UTC, tuxology requested changes
Please see comments. I've requested clarifications. We can't use hardcoded values to the approach to fix this may have to change

2023-03-28 02:15 UTC, tuxology commented on zubhub_frontend/zubhub/src/views/login/Login.jsx
> +                        label="Username Or Email"
We can't hardcode this since this must be coming from translation text isn't it?

2023-03-28 02:15 UTC, tuxology commented on zubhub_frontend/zubhub/src/views/login/Login.jsx
> +                        label="password"
Same as above

2023-03-28 02:15 UTC, tuxology commented on zubhub_frontend/zubhub/src/views/password_reset/PasswordReset.jsx
> +                        label="email"
Same as above

2023-09-08 21:23 UTC, closed without merging