fix: fixes assertion/serializers issues
unstructuredstudio/zubhub pull request #806
Opened 2023-10-05 21:31 UTC by yokwejuste

## Summary

Description of PR here...
Closes #785
closes #788

## Changes

- [Serializers](https://github.com/unstructuredstudio/zubhub/compare/master...yokwejuste:zubhub:master#diff-7ec97ce6e091ad58f047c0eec8e86039fbeb97b509b9a3d3d7869819237bfbec)
- [View file](https://github.com/unstructuredstudio/zubhub/compare/master...yokwejuste:zubhub:master#diff-4ff5ce7a0e1fe15ea8b05202336fbcf1a13c018a83cbfb1ba9db06567e42cbc5)

## Screenshots
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/e6c7a020-57bf-4b87-8853-e29b44f61bd1)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/fcf32370-c976-4501-b036-00fa27d8bcbb)

## Requests / Responses

2023-10-14 04:14 UTC, yokwejuste commented
@tuxology can you review this?

2023-10-15 17:18 UTC, tuxology requested changes
See comments above 👆

2023-10-15 17:18 UTC, tuxology commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
Why is this named as `TemplateProfileSerializer`?

2023-10-15 17:18 UTC, tuxology commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
@yokwejuste updates?

2023-10-15 17:22 UTC, yokwejuste commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
I got the name from the error display on #785 and decided to do something generic

2023-10-15 18:46 UTC, tuxology commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
So this should be `TeamProfileSerializer` and not `TemplateProfileSerialize` am I right?

2023-10-15 18:50 UTC, yokwejuste commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
Ohh I yes it is, so should I edit it ?

2023-10-15 18:54 UTC, yokwejuste commented on zubhub_backend/zubhub/creators/views.py
> +    serializer_class = TemplateProfileSerializer
```suggestion
    serializer_class = TeamProfileSerializer
```

2023-10-15 18:54 UTC, yokwejuste commented on zubhub_backend/zubhub/creators/views.py
> +                          AddGroupMembersSerializer, CreatorGroupMembershipSerializer, TemplateProfileSerializer)
```suggestion
                          AddGroupMembersSerializer, CreatorGroupMembershipSerializer, TeamProfileSerializer)
```

2023-10-15 18:54 UTC, yokwejuste commented on zubhub_backend/zubhub/creators/serializers.py
> +class TemplateProfileSerializer(serializers.Serializer):
```suggestion
class TeamProfileSerializer(serializers.Serializer):
```

2023-10-15 19:29 UTC, tuxology approved these changes

2023-10-15 19:30 UTC, merged