fix: match overlay border radius to card's
unstructuredstudio/zubhub pull request #844
Opened 2023-10-08 18:56 UTC by brrkrmn

## Summary

The overlay border had a mismatch border radius. This PR addresses that.

## Changes

- Changes overlay border radius to 15px.

## Videos

Before:

https://github.com/unstructuredstudio/zubhub/assets/92817363/a433e034-2af5-4104-bba6-aefc8253a30d

After:

https://github.com/unstructuredstudio/zubhub/assets/92817363/a7c56f6d-ca03-487c-919d-82ca02741877

2023-10-09 06:44 UTC, coderatomy requested changes
Nice work @brrkrmn.  Just a requirement missed

2023-10-09 06:44 UTC, coderatomy commented on zubhub_frontend/zubhub/src/views/create_team/step3/step3.styles.js
> +        borderRadius: '15px',
Can you please attach UI differences `before  and after` the changes in the summary above. It's easier for reviewers. 

We actually have to run this locally and test these changes to confirm if it is actually what you say it is. So attaching some screenshots is crucial more so for such UI changes

2023-10-09 06:46 UTC, coderatomy approved these changes

2023-10-11 00:17 UTC, tuxology approved these changes

2023-10-11 00:55 UTC, merged