None - removed from the Project & Activity Section
unstructuredstudio/zubhub pull request #911
Opened 2023-10-16 12:54 UTC by Urmilasc

**Description : ** 
This PR removes this line " Select none if you are unsure about your category." from both the Project and Activity Section

Closes #875 

**Changes :**

Removed the line " Select none if you are unsure about your category." from the create Project and Activity Create Area.

**Steps to test : **

- Login to Zuphub
- Click on the create project present on the side navbar 
- After clicking on that , start to create a project and go upto 3rd step , there the line of which come as an helperText has been removed .

**Screenshot after change : **

![helper](https://github.com/unstructuredstudio/zubhub/assets/97338915/2e7fff31-8e84-4cb6-8ba2-a73be77e0d19)

Please review it and let me know the changes to be done !!

2023-10-16 15:53 UTC, aqsaaqeel commented
We should add a none option too in case the user does not want to put it in a category.

2023-10-16 16:46 UTC, Urmilasc commented
Okay @aqsaaqeel , Thankyou for confirming , try to implement that one !!

2023-10-17 00:39 UTC, tuxology commented
> We should add a none option too in case the user does not want to put it in a category.

@aqsaaqeel I think in backend we don't have a None category (I may be wrong). It is ideal just to let user select any of the category, hence what @Urmilasc did is ok. We however need to pass this text via translation

2023-10-17 00:40 UTC, tuxology requested changes
Use translation string for this

2023-10-17 01:07 UTC, srish approved these changes

2023-10-17 01:07 UTC, tuxology approved these changes
Actually its fine, we can merge this

2023-10-18 02:43 UTC, merged